[toolchain]
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
trustchain_notary = "CvEK7knkMGSE4jw9HxNjHndxdChKW6XAxN4wThk3dkLT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
# UPDATED: Using the space-free symbolic link
wallet = "/home/freedomwithin/solana-keys/demo.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
