[toolchain]
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
trustchain_notary = "5nbMQKE3kpUPpXRw7TdnReJDoeQfKBgLTnrfuENZn3Xe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/freedomwithin/Documents/Tech/1_GitHub_Reops/TrustChain_documentation/Wallets-Testing/current_in_use_for_demo.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
